---
jupyter: python3
execute:
  enabled: false
---

# Gene Finder Analysis

Authors: Ophelia Lonzo and Hayden Zangerl-Salter

Run the cell below each time the notebook is started or restarted to
ensure that if you change any code in the library, this notebook will
use the latest version of the library code.

```{python}
%load_ext autoreload
%autoreload 2
```

To analyze the SARS-CoV-2 virus, we wrote code to use the protein-BLAST search engine to determine which of protein-coding SARS-CoV-2 genes may encode key proteins of the virus. 

Starting off, we imported a genome from the protein-BLAST search engine.

```{python}
from gene_finder import *
from helpers import load_fasta_file
genome = load_fasta_file("data/NC_045512.2.fa")
len(genome)
```

Then, we took only ORFS from both the imported genome as well as the reverse complementary genome, and also shuffled the genome 1500 times, checking the strand and it's reverse compliment for the longest ORF. The minimum ORF length among all 1500 random sequences is kept track of here as threshold.

```{python}
threshold = noncoding_orf_threshold(genome, 1500)
threshold
orfs = find_all_orfs_both_strands(genome)
len(orfs)
```

We then use threshold to filter out any sequences that are likely too short to produce useful proteins. We add suitable ORFs to the list candidate_orfs.

```{python}
candidate_orfs = []
for orf in orfs:
    if len(orf) > threshold:
        candidate_orfs.append(orf)
len(candidate_orfs)
```

We then store the protein sequence for every ORF in candidate_orfs. These proteins may give us a better understanding of how the virus works, and also give us possible routes to better treatments or vaccines.  

```{python}
proteins = []
for orf in candidate_orfs:
    proteins.append(encode_amino_acids(orf))
proteins
```

Feeding our results into BLAST returned ORF1ab, ORF3a, envelope protein, ORF7a, surface glycoprotein, nucleocapsid phosphoprotein, membrane glycoprotein, ORF8, and ORF9b. A few returned nothing, and some of the results seem to be hypothetical proteins not actually found in the disease, but rather generated by researchers doing similar tests.

